[workspace]
members = [
  "./pedersen",
  "./t256",
  "./t384",
  "./acl",
  "./boomerang",
  "./macros",
  "./bulletproofs",
  "./rewards-proof"
  "./end2end-example/client",
  "./end2end-example/server",
]
resolver = "2"
